"use client";
import {useEffect,useMemo,useState} from 'react';import type{Marker}from'@/lib/types';import LanguageSwitcher from './LanguageSwitcher';import{useLanguage}from'./LanguageProvider';
const TYPES=['metal','crystal','obsidian','oil','oilvein','sulfur','silica','blackpearls','element','redingot','diamondingot','goldingot','cave','artifact','loot','creature'];
type User={id:string;name:string;email:string;role:string;banned:boolean;banned_reason?:string;created_at:string;marker_count:number;approved_count:number;rejected_count:number};
type Creature={id:number;slug:string;name:string;active:boolean;marker_count:number;icon_url?:string|null};
type Resource={id:number;type_key:string;name_cs:string;name_en:string;active:boolean;marker_count:number;icon_url?:string|null;color:string};
const RESOURCE_ICON_SVGS:Record<string,string>={
 metal:`<svg viewBox="0 0 48 48"><path fill="#b9c4cf" d="M8 31 15 15l11-5 7 8 8 5-5 15H17z"/><path fill="#6f7f8e" d="m8 31 13-7 15 14H17z"/><path fill="#eef4f8" d="m15 15 11-5-5 14-13 7z"/></svg>`,
 crystal:`<svg viewBox="0 0 48 48"><path fill="#a93cff" d="m24 4 9 16-9 24-9-24z"/><path fill="#e9a8ff" d="m24 4 2 28-11-12z"/><path fill="#6e19c8" d="m24 44 2-12 7-12z"/><path fill="#8a25ef" d="M8 21h9l4 21-12-9zM40 21h-9l-4 21 12-9z"/></svg>`,
 obsidian:`<svg viewBox="0 0 48 48"><path fill="#1b1526" d="M8 30 16 12l13-4 11 13-5 18H16z"/><path fill="#7c3fd1" d="m16 12 13-4-7 18-14 4z"/><path fill="#372050" d="m8 30 14-4 13 13H16z"/><path fill="#d596ff" d="m28 11 5 9-8 4z"/></svg>`,
 oil:`<svg viewBox="0 0 48 48"><path fill="#f3a62f" d="M24 4C18 14 11 22 11 31a13 13 0 0 0 26 0C37 22 30 14 24 4z"/><path fill="#ffe29a" d="M20 14c-3 7-6 12-6 17 0 5 3 8 7 10-2-4-2-9 1-14 2-4 3-8-2-13z"/></svg>`,
 oilvein:`<svg viewBox="0 0 48 48"><path fill="#d83f27" d="M10 13h28v29H10z"/><path fill="#ff714d" d="M13 16h22v7H13z"/><path fill="#671b19" d="M8 10h32v6H8zM8 39h32v5H8z"/><circle cx="24" cy="31" r="6" fill="#ffb44d"/><path fill="#35120f" d="M22 26h4v10h-4z"/></svg>`,
 sulfur:`<svg viewBox="0 0 48 48"><path fill="#f5c928" d="M7 32 15 16l10-6 8 7 9 8-6 14H16z"/><path fill="#fff06a" d="m15 16 10-6-4 16-14 6z"/><path fill="#bd7e0a" d="m7 32 14-6 15 13H16z"/></svg>`,
 silica:`<svg viewBox="0 0 48 48"><circle cx="17" cy="26" r="9" fill="#e8f3f8"/><circle cx="29" cy="18" r="9" fill="#fff"/><circle cx="32" cy="31" r="9" fill="#cbdce5"/><circle cx="27" cy="15" r="3" fill="#fff"/></svg>`,
 blackpearls:`<svg viewBox="0 0 48 48"><circle cx="17" cy="26" r="9" fill="#21192d"/><circle cx="29" cy="18" r="9" fill="#4a315f"/><circle cx="32" cy="31" r="9" fill="#15111d"/><circle cx="27" cy="15" r="3" fill="#bd8df4"/></svg>`,
 element:`<svg viewBox="0 0 48 48"><circle cx="14" cy="30" r="5" fill="#28e0c1"/><circle cx="25" cy="34" r="6" fill="#1bb7c9"/><circle cx="34" cy="26" r="4.5" fill="#69f5dd"/><circle cx="22" cy="21" r="4" fill="#a8fff0"/><circle cx="31" cy="16" r="3" fill="#27e1c1"/><path fill="#d9fff8" d="m13 13 1.8 4.2L19 19l-4.2 1.8L13 25l-1.8-4.2L7 19l4.2-1.8z"/></svg>`,
 redingot:`<svg viewBox="0 0 48 48"><path fill="#5d1019" d="M7 30 14 17h25l3 13-8 9H12z"/><path fill="#d92f42" d="m14 17 5-7h19l1 7z"/><path fill="#ff6674" d="M16 19h21l2 8H11z"/><path fill="#ffb0b7" d="M19 13h16l2 3H17z"/><path fill="#8f1c2b" d="M11 27h28l-5 9H14z"/></svg>`,
 diamondingot:`<svg viewBox="0 0 48 48"><path fill="#15546c" d="M7 30 14 17h25l3 13-8 9H12z"/><path fill="#35c8e8" d="m14 17 5-7h19l1 7z"/><path fill="#78edff" d="M16 19h21l2 8H11z"/><path fill="#e0fbff" d="M19 13h16l2 3H17z"/><path fill="#2493b4" d="M11 27h28l-5 9H14z"/></svg>`,
 goldingot:`<svg viewBox="0 0 48 48"><path fill="#80530a" d="M7 30 14 17h25l3 13-8 9H12z"/><path fill="#d99b18" d="m14 17 5-7h19l1 7z"/><path fill="#ffc83d" d="M16 19h21l2 8H11z"/><path fill="#fff09a" d="M19 13h16l2 3H17z"/><path fill="#b8780d" d="M11 27h28l-5 9H14z"/></svg>`
};
export default function AdminDashboard(){const{language}=useLanguage();const[reports,setReports]=useState<any[]>([]),[topUsers,setTopUsers]=useState<any[]>([]),[typeStats,setTypeStats]=useState<any[]>([]);const[maintenance,setMaintenance]=useState<boolean|null>(null),[maintenanceBusy,setMaintenanceBusy]=useState(false),[maintenanceError,setMaintenanceError]=useState(''),[tab,setTab]=useState('overview'),[markers,setMarkers]=useState<any[]>([]),[users,setUsers]=useState<User[]>([]),[stats,setStats]=useState<any>({}),[activity,setActivity]=useState<any[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[edit,setEdit]=useState<any>(null),[userDetail,setUserDetail]=useState<User|null>(null),[ban,setBan]=useState<User|null>(null),[reason,setReason]=useState(''),[del,setDel]=useState<any>(null),[busy,setBusy]=useState(false),[photo,setPhoto]=useState<File|null>(null),[creatures,setCreatures]=useState<Creature[]>([]),[newCreature,setNewCreature]=useState(''),[creatureIconFile,setCreatureIconFile]=useState<File|null>(null),[resources,setResources]=useState<Resource[]>([]),[newResource,setNewResource]=useState({nameCs:'',nameEn:'',color:'#27e1c1'}),[resourceIconFile,setResourceIconFile]=useState<File|null>(null),[selectedIds,setSelectedIds]=useState<number[]>([]);
 async function load(){const [m,u,s,c,rr,rp]=await Promise.all([fetch('/api/admin/markers'),fetch('/api/admin/users'),fetch('/api/admin/stats'),fetch('/api/admin/creatures'),fetch('/api/admin/resources'),fetch('/api/admin/reports')]);if(m.ok)setMarkers(await m.json());if(u.ok)setUsers(await u.json());if(c.ok)setCreatures(await c.json());if(rr.ok)setResources(await rr.json());if(rp.ok)setReports(await rp.json());if(s.ok){const x=await s.json();setStats(x.stats||{});setActivity(x.activity||[]);setTopUsers(x.top||[]);setTypeStats(x.types||[])}}useEffect(()=>{load();fetch('/api/admin/maintenance',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>setMaintenance(!!d.enabled)).catch(()=>setMaintenanceError(language==='cs'?'Nepodařilo se načíst stav údržby.':'Failed to load maintenance status.'))},[]);
 const filtered=useMemo(()=>markers.filter(m=>(status==='all'||m.approval_status===status)&&(`${m.name} ${m.submitter_name||''} ${m.submitter_email||''}`).toLowerCase().includes(q.toLowerCase())),[markers,status,q]);const fu=useMemo(()=>users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(q.toLowerCase())),[users,q]);
 async function bulkModerate(action:'approve'|'reject'){if(!selectedIds.length)return;setBusy(true);try{const r=await fetch('/api/admin/markers/bulk',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({ids:selectedIds,action})});if(!r.ok)throw new Error(`HTTP ${r.status}`);setSelectedIds([]);await load()}catch(e){alert((language==='cs'?'Hromadná akce selhala: ':'Bulk action failed: ')+String(e))}finally{setBusy(false)}}
 async function moderate(id:number,action:string){setBusy(true);await fetch(`/api/admin/markers/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});await load();setBusy(false)}
 async function saveMarker(){if(!edit)return;setBusy(true);let image=edit.image_url;if(photo){const fd=new FormData();fd.append('file',photo);const r=await fetch('/api/blob/upload',{method:'POST',body:fd});if(!r.ok){alert('Fotku se nepodařilo nahrát.');setBusy(false);return}image=(await r.json()).url}await fetch(`/api/admin/markers/${edit.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'update',name:edit.name,type:edit.type,lat:Number(edit.lat),lon:Number(edit.lon),note:edit.note||'',image_url:image||null,approval_status:edit.approval_status,featured:!!edit.featured})});setEdit(null);setPhoto(null);await load();setBusy(false)}
 async function uploadAdminIcon(file:File|null){if(!file)return null;const fd=new FormData();fd.append('file',file);const r=await fetch('/api/blob/upload',{method:'POST',body:fd});if(!r.ok)throw new Error('upload');return (await r.json()).url as string}
 async function addCreature(){const name=newCreature.trim();if(name.length<2)return;const slug=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');setBusy(true);try{const iconUrl=await uploadAdminIcon(creatureIconFile);await fetch('/api/admin/creatures',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,slug,active:true,iconUrl})});setNewCreature('');setCreatureIconFile(null);await load()}finally{setBusy(false)}}
 async function toggleCreature(c:Creature){setBusy(true);await fetch(`/api/admin/creatures/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:c.name,active:!c.active,iconUrl:c.icon_url||null})});await load();setBusy(false)}
 async function changeCreatureIcon(c:Creature,file:File|null){if(!file)return;setBusy(true);try{const iconUrl=await uploadAdminIcon(file);await fetch(`/api/admin/creatures/${c.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:c.name,active:c.active,iconUrl})});await load()}finally{setBusy(false)}}
 async function addResource(){const cs=newResource.nameCs.trim(),en=newResource.nameEn.trim();if(cs.length<2||en.length<2)return;const typeKey='res-'+en.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');setBusy(true);try{const iconUrl=await uploadAdminIcon(resourceIconFile);await fetch('/api/admin/resources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({typeKey,nameCs:cs,nameEn:en,color:newResource.color,iconUrl})});setNewResource({nameCs:'',nameEn:'',color:'#27e1c1'});setResourceIconFile(null);await load()}finally{setBusy(false)}}
 async function toggleResource(r:Resource){setBusy(true);await fetch(`/api/admin/resources/${r.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({nameCs:r.name_cs,nameEn:r.name_en,color:r.color,active:!r.active,iconUrl:r.icon_url||null})});await load();setBusy(false)}
 async function changeResourceIcon(r:Resource,file:File|null){if(!file)return;setBusy(true);try{const iconUrl=await uploadAdminIcon(file);await fetch(`/api/admin/resources/${r.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({nameCs:r.name_cs,nameEn:r.name_en,color:r.color,active:r.active,iconUrl})});await load()}finally{setBusy(false)}}
 async function banUser(action:'ban'|'unban',u:User){setBusy(true);await fetch(`/api/admin/users/${u.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,reason})});setBan(null);setReason('');setUserDetail(null);await load();setBusy(false)}
 async function promoteAdmin(u:User){if(u.role==='admin')return;if(!confirm(`Opravdu chceš jmenovat ${u.name} administrátorem? Získá plný přístup do administrace.`))return;setBusy(true);const r=await fetch(`/api/admin/users/${u.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'promote_admin'})});if(!r.ok)alert('Uživatele se nepodařilo jmenovat administrátorem.');setUserDetail(null);await load();setBusy(false)}
 return <div className="admin-v2"><header className="admin-v2-head"><div><div className="kicker">THARAT CONTROL CENTER</div><h1>Admin Panel V2</h1><p>Správa uživatelů, markerů a komunitního obsahu</p></div><div className="admin-top-actions"><LanguageSwitcher/><a className="ghost-button" href="/admin/feedback">💬 FEEDBACK</a><a className="ghost-button" href="/">← ZPĚT NA MAPU</a></div></header><nav className="admin-v2-tabs">{[['overview','PŘEHLED'],['maintenance',language==='cs'?'🛠 ÚDRŽBA':'🛠 MAINTENANCE'],['pending',`KE SCHVÁLENÍ (${markers.filter(m=>m.approval_status==='pending').length})`],['markers','MARKERY'],['users','UŽIVATELÉ'],['creatures','TVOROVÉ'],['resources','SUROVINY'],['reports',language==='cs'?`HLÁŠENÍ (${reports.length})`:`REPORTS (${reports.length})`]].map(x=><button className={tab===x[0]?'active':''} onClick={()=>{setTab(x[0]);setQ('')}} key={x[0]}>{x[1]}</button>)}</nav>

 {tab==='maintenance'&&<section className="admin-panel"><div className="kicker">SITE CONTROL</div><h2>{language==='cs'?'Režim údržby':'Maintenance mode'}</h2><p>{language==='cs'?'Po zapnutí uvidí návštěvníci stránku s oznámením o údržbě. Administrátoři mohou dál používat mapu i administrační panel. Moderátoři během údržby přístup nemají.':'When enabled, visitors see a maintenance notice. Administrators retain access to the map and admin panel. Moderators are not exempt.'}</p><div className="maintenance-switch"><span className="maintenance-status">{maintenance===null?'…':maintenance?(language==='cs'?'🔴 ÚDRŽBA ZAPNUTA':'🔴 MAINTENANCE ON'):(language==='cs'?'🟢 WEB JE VEŘEJNÝ':'🟢 SITE IS PUBLIC')}</span><button className={maintenance?'accent-button':'danger-button'} disabled={maintenanceBusy||maintenance===null} onClick={async()=>{const next=!maintenance;if(!confirm(next?(language==='cs'?'Opravdu zapnout režim údržby?':'Enable maintenance mode?'):(language==='cs'?'Opravdu znovu zpřístupnit web veřejnosti?':'Make the website public again?')))return;setMaintenanceBusy(true);setMaintenanceError('');try{const r=await fetch('/api/admin/maintenance',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:next})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();setMaintenance(!!data.enabled)}catch(e){setMaintenanceError(String(e))}finally{setMaintenanceBusy(false)}}}>{maintenanceBusy?'…':maintenance?(language==='cs'?'✓ VYPNOUT ÚDRŽBU':'✓ DISABLE MAINTENANCE'):(language==='cs'?'⚒ ZAPNOUT ÚDRŽBU':'⚒ ENABLE MAINTENANCE')}</button></div>{maintenanceError&&<p className="form-error">{maintenanceError}</p>}</section>}
 {tab==='overview'&&<><div className="admin-metrics admin-metrics-wide">{[[language==='cs'?'UŽIVATELÉ':'USERS',stats.users||0,'👥'],[language==='cs'?'NOVÍ / 7 DNÍ':'NEW / 7 DAYS',stats.new_users_7d||0,'✨'],[language==='cs'?'MARKERY':'MARKERS',stats.markers||0,'📍'],[language==='cs'?'NOVÉ / 7 DNÍ':'NEW / 7 DAYS',stats.new_markers_7d||0,'🆕'],[language==='cs'?'ČEKAJÍCÍ':'PENDING',stats.pending||0,'⏳'],[language==='cs'?'HLÁŠENÍ':'REPORTS',stats.reports||0,'⚑']].map(x=><div className="metric" key={String(x[0])+String(x[2])}><i>{x[2]}</i><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="admin-stat-grids"><section className="admin-panel"><h2>{language==='cs'?'TOP PŘISPĚVATELÉ':'TOP CONTRIBUTORS'}</h2>{topUsers.map((u:any,i:number)=><div className="stat-line" key={u.id}><b>#{i+1} {u.name}</b><span>{u.count}</span></div>)}</section><section className="admin-panel"><h2>{language==='cs'?'NEJČASTĚJŠÍ TYPY':'TOP MARKER TYPES'}</h2>{typeStats.map((x:any)=><div className="stat-line" key={x.type}><b>{x.type}</b><span>{x.count}</span></div>)}</section></div><section className="admin-panel"><h2>{language==='cs'?'POSLEDNÍ ADMIN AKTIVITA':'LATEST ADMIN ACTIVITY'}</h2>{activity.length?activity.map(a=><div className="activity" key={a.id}><b>{a.admin_name||'Admin'}</b><span>{a.action.replaceAll('_',' ')}</span><time>{new Date(a.created_at).toLocaleString('cs-CZ')}</time></div>):<div className="empty">Zatím žádná zaznamenaná aktivita.</div>}</section></>}
 {(tab==='pending'||tab==='markers')&&<section className="admin-panel"><div className="admin-tools"><input placeholder="🔎 Hledat marker nebo autora…" value={q} onChange={e=>setQ(e.target.value)}/><button className="ghost-button" onClick={()=>setSelectedIds(filtered.filter(m=>tab!=='pending'||m.approval_status==='pending').map(m=>m.id))}>VYBRAT VŠE</button>{selectedIds.length>0&&<><button className="accent-button" onClick={()=>bulkModerate('approve')}>✓ SCHVÁLIT ({selectedIds.length})</button><button className="danger-button" onClick={()=>bulkModerate('reject')}>✕ ZAMÍTNOUT</button></>}{tab==='markers'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Všechny stavy</option><option value="approved">Schválené</option><option value="pending">Čekající</option><option value="rejected">Zamítnuté</option></select>}</div><div className="admin-table"><div className="admin-tr admin-th"><span>MARKER</span><span>KATEGORIE</span><span>SOUŘADNICE</span><span>AUTOR</span><span>STAV</span><span>AKCE</span></div>{filtered.filter(m=>tab!=='pending'||m.approval_status==='pending').map(m=><div className="admin-tr" key={m.id}><span className="marker-cell"><input type="checkbox" checked={selectedIds.includes(m.id)} onChange={e=>setSelectedIds(v=>e.target.checked?[...v,m.id]:v.filter(x=>x!==m.id))}/>{m.image_url&&<img src={m.image_url}/>}<b>{m.featured&&<em className="featured-mini">⭐</em>}{m.name}</b></span><span>{m.type}</span><span>{Number(m.lat).toFixed(2)} / {Number(m.lon).toFixed(2)}</span><span>{m.submitter_name||m.submitter_email||'—'}</span><span><em className={`state ${m.approval_status}`}>{m.approval_status}</em></span><span className="row-actions"><button onClick={()=>setEdit({...m})}>UPRAVIT</button>{m.approval_status!=='approved'&&<button onClick={()=>moderate(m.id,'approve')}>✓</button>}{m.approval_status!=='rejected'&&<button onClick={()=>moderate(m.id,'reject')}>✕</button>}<button className="danger" onClick={()=>setDel(m)}>🗑</button></span></div>)}</div></section>}
 {tab==='users'&&<section className="admin-panel"><div className="admin-tools"><input placeholder="🔎 Hledat jméno nebo e-mail…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="admin-table users"><div className="admin-tr admin-th"><span>UŽIVATEL</span><span>E-MAIL</span><span>ROLE</span><span>MARKERY</span><span>REGISTRACE</span><span>STAV / AKCE</span></div>{fu.map(u=><div className="admin-tr" key={u.id}><span><b>{u.name}</b></span><span>{u.email}</span><span>{u.role}</span><span>{u.marker_count}</span><span>{new Date(u.created_at).toLocaleDateString('cs-CZ')}</span><span className="row-actions"><em className={`state ${u.banned?'rejected':'approved'}`}>{u.banned?'BLOKOVÁN':'AKTIVNÍ'}</em><button onClick={()=>setUserDetail(u)}>DETAIL</button></span></div>)}</div></section>}
 {tab==='creatures'&&<section className="admin-panel"><div className="creature-admin-form"><label><span>NÁZEV TVORA</span><input placeholder="Např. Baryonyx" value={newCreature} onChange={e=>setNewCreature(e.target.value)}/></label><label className="icon-upload-field"><span>IKONA</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setCreatureIconFile(e.target.files?.[0]||null)}/></label><button className="accent-button" disabled={busy||newCreature.trim().length<2} onClick={addCreature}>＋ PŘIDAT TVORA</button></div><div className="admin-section-scroll creature-admin-list"><div className="creature-admin-row creature-admin-head"><span>IKONA</span><span>TVOR</span><span>SLUG</span><span>MARKERY</span><span>STAV</span></div>{creatures.map(c=><div className="creature-admin-row" key={c.id}><label title="Klikni pro změnu ikony"><img className="admin-icon-preview" src={c.icon_url||`/creatures/${c.slug}.svg`} onError={e=>{e.currentTarget.src='/creatures/default.svg'}}/><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>changeCreatureIcon(c,e.target.files?.[0]||null)}/></label><b>{c.name}</b><code>{c.slug}</code><span>{c.marker_count}</span><button className={c.active?'active':'inactive'} onClick={()=>toggleCreature(c)}>{c.active?'AKTIVNÍ':'SKRYTÝ'}</button></div>)}</div></section>}
 {tab==='resources'&&<section className="admin-panel"><div className="kicker">RESOURCE MANAGER</div><h2>Správa surovin</h2><div className="resource-admin-form"><label>ČESKÝ NÁZEV<input value={newResource.nameCs} onChange={e=>setNewResource({...newResource,nameCs:e.target.value})} placeholder="Např. Červený krystal"/></label><label>ANGLICKÝ NÁZEV<input value={newResource.nameEn} onChange={e=>setNewResource({...newResource,nameEn:e.target.value})} placeholder="Red Crystal"/></label><label>BARVA<input type="color" value={newResource.color} onChange={e=>setNewResource({...newResource,color:e.target.value})}/></label><label className="icon-upload-field">IKONA<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setResourceIconFile(e.target.files?.[0]||null)}/></label><button className="accent-button" disabled={busy||newResource.nameCs.trim().length<2||newResource.nameEn.trim().length<2} onClick={addResource}>＋ PŘIDAT SUROVINU</button></div><div className="admin-section-scroll"><div className="resource-admin-row"><b>IKONA</b><b>ČESKY</b><b>ANGLICKY</b><b>MARKERY</b><b>STAV</b></div>{resources.map(r=><div className="resource-admin-row" key={r.id}><label className="admin-icon-picker" title="Klikni pro změnu ikony">{r.icon_url?<img className="admin-icon-preview" src={r.icon_url} alt=""/>:<span className="admin-icon-preview builtin-resource-icon" style={{'--icon-color':r.color} as any} dangerouslySetInnerHTML={{__html:RESOURCE_ICON_SVGS[r.type_key]||RESOURCE_ICON_SVGS.metal}}/>}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>changeResourceIcon(r,e.target.files?.[0]||null)}/></label><b>{r.name_cs}</b><span>{r.name_en}</span><span>{r.marker_count}</span><button className={r.active?'accent-button':'ghost-button'} onClick={()=>toggleResource(r)}>{r.active?'AKTIVNÍ':'SKRYTÁ'}</button></div>)}</div></section>}

 {tab==='reports'&&<section className="admin-panel"><div className="kicker">COMMUNITY REPORTS</div><h2>{language==='cs'?'Hlášení lokací':'Location reports'}</h2><div className="report-admin-list">{reports.length?reports.map((r:any)=><div className="report-admin-row" key={r.id}><div><b>⚑ {r.marker_name}</b><span>{r.reason}</span><p>{r.detail||'—'}</p><small>{r.reporter_name||'—'} · {new Date(r.created_at).toLocaleString(language==='cs'?'cs-CZ':'en-US')}</small></div><div><a className="ghost-button" href={`/?marker=${r.marker_id}`}>{language==='cs'?'OTEVŘÍT':'OPEN'}</a><button className="danger-button" onClick={async()=>{await fetch('/api/admin/reports',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:r.id})});await load()}}>{language==='cs'?'VYŘEŠENO':'RESOLVED'}</button></div></div>):<div className="empty">{language==='cs'?'Žádná hlášení.':'No reports.'}</div>}</div></section>}
 {edit&&<div className="modal-bg"><div className="admin-editor"><button className="detail-x" onClick={()=>setEdit(null)}>×</button><div className="kicker">MARKER EDITOR</div><h2>Upravit marker #{edit.id}</h2><label>NÁZEV<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>KATEGORIE<select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})}>{[...TYPES,...resources.map(r=>r.type_key)].map(x=><option key={x}>{resources.find(r=>r.type_key===x)?.name_cs||x}</option>)}</select></label><div className="two"><label>LAT<input type="number" step=".01" value={edit.lat} onChange={e=>setEdit({...edit,lat:e.target.value})}/></label><label>LON<input type="number" step=".01" value={edit.lon} onChange={e=>setEdit({...edit,lon:e.target.value})}/></label></div><label>POPIS<textarea value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})}/></label><label>STAV<select value={edit.approval_status} onChange={e=>setEdit({...edit,approval_status:e.target.value})}><option value="pending">Čeká</option><option value="approved">Schválený</option><option value="rejected">Zamítnutý</option></select></label><label className="featured-admin-toggle"><input type="checkbox" checked={!!edit.featured} onChange={e=>setEdit({...edit,featured:e.target.checked})}/><span>⭐ {language==='cs'?'DOPORUČENÝ MARKER':'FEATURED MARKER'}</span><small>{language==='cs'?'Zvýrazní marker na mapě a v detailu.':'Highlights the marker on the map and in its detail.'}</small></label><div className="admin-photo"><div className="admin-photo-head"><b>FOTOGRAFIE MARKERU</b><small>JPG, PNG nebo WebP</small></div>{edit.image_url&&<div className="admin-photo-preview"><img src={edit.image_url} alt="Fotografie markeru"/><button type="button" className="admin-remove-photo" onClick={()=>{setPhoto(null);setEdit({...edit,image_url:null})}}>🗑 ODSTRANIT FOTKU</button></div>}<label className="admin-file-picker"><span>{edit.image_url?"ZMĚNIT FOTKU":"NAHRÁT FOTKU"}</span><small>{photo?photo.name:"Vybrat soubor"}</small><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label></div><div className="form-actions"><button className="ghost-button" onClick={()=>setEdit(null)}>ZRUŠIT</button><button className="accent-button" disabled={busy} onClick={saveMarker}>💾 ULOŽIT ZMĚNY</button></div></div></div>}
 {userDetail&&<div className="modal-bg"><div className="admin-editor"><button className="detail-x" onClick={()=>setUserDetail(null)}>×</button><div className="kicker">USER PROFILE</div><h2>{userDetail.name}</h2><p>{userDetail.email}</p><div className="user-metrics"><div><b>{userDetail.marker_count}</b><span>MARKERY</span></div><div><b>{userDetail.approved_count}</b><span>SCHVÁLENO</span></div><div><b>{userDetail.rejected_count}</b><span>ZAMÍTNUTO</span></div></div>{userDetail.banned&&<div className="ban-reason">Důvod blokace: {userDetail.banned_reason||'—'}</div>}<div className="admin-role-box"><span>{language==='cs'?'ROLE ÚČTU':'ACCOUNT ROLE'}</span><b>{userDetail.role==='admin'?(language==='cs'?'ADMINISTRÁTOR':'ADMINISTRATOR'):userDetail.role==='moderator'?(language==='cs'?'MODERÁTOR':'MODERATOR'):(language==='cs'?'UŽIVATEL':'USER')}</b>
{userDetail.role!=='admin'&&<button className="accent-button" disabled={busy} onClick={()=>promoteAdmin(userDetail)}>★ {language==='cs'?'JMENOVAT ADMINEM':'MAKE ADMIN'}</button>}
{userDetail.role!=='admin'&&<button className="ghost-button" disabled={busy} onClick={async()=>{
 const action=userDetail.role==='moderator'?'make_user':'make_moderator';
 if(!confirm(language==='cs'?'Opravdu změnit roli tohoto uživatele?':'Change this user’s role?'))return;
 setBusy(true);
 try{
 const r=await fetch(`/api/admin/users/${userDetail.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action})});
 if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(data.error||`HTTP ${r.status}`);}
 await load();setUserDetail(null);
 }catch(e){alert((language==='cs'?'Změna role selhala: ':'Role change failed: ')+(e instanceof Error?e.message:String(e)));}
 finally{setBusy(false);}
 }}>{userDetail.role==='moderator'?(language==='cs'?'ODEBRAT MODERÁTORA':'REMOVE MODERATOR'):(language==='cs'?'🛡 JMENOVAT MODERÁTOREM':'🛡 MAKE MODERATOR')}</button>}
<button className="ghost-button" disabled={busy} onClick={async()=>{const r=prompt(language==='cs'?'Text varování:':'Warning message:');if(!r)return;setBusy(true);try{const res=await fetch(`/api/admin/users/${userDetail.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'warn',reason:r})});if(!res.ok)throw new Error(`HTTP ${res.status}`);alert(language==='cs'?'Varování uloženo.':'Warning saved.');await load()}catch(e){alert(String(e))}finally{setBusy(false)}}}>⚠ {language==='cs'?'VAROVAT':'WARN'}</button>
<button className="danger-button" disabled={busy} onClick={async()=>{const input=prompt(language==='cs'?'Dočasný ban na kolik dní?':'Temporary ban for how many days?','7');if(input===null)return;const days=Number(input);if(!Number.isInteger(days)||days<1||days>365){alert(language==='cs'?'Zadej 1 až 365 dní.':'Enter 1 to 365 days.');return;}const reason=prompt(language==='cs'?'Důvod:':'Reason:')||(language==='cs'?'Dočasná blokace':'Temporary ban');setBusy(true);try{const r=await fetch(`/api/admin/users/${userDetail.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'temp_ban',days,reason})});if(!r.ok)throw new Error(`HTTP ${r.status}`);setUserDetail(null);await load()}catch(e){alert(String(e))}finally{setBusy(false)}}}>⏱ {language==='cs'?'DOČASNÝ BAN':'TEMPORARY BAN'}</button></div><div className="form-actions">{userDetail.banned?<button className="accent-button" onClick={()=>banUser('unban',userDetail)}>✓ ODBLOKOVAT</button>:<button className="danger-button" onClick={()=>setBan(userDetail)}>🚫 ZABLOKOVAT UŽIVATELE</button>}</div></div></div>}
 {ban&&<div className="modal-bg"><div className="confirm-card"><div className="kicker">⚠ BLOKACE ÚČTU</div><h2>Zablokovat {ban.name}?</h2><p>Uživatel se nebude moci přihlásit ani přidávat markery.</p><textarea placeholder="Důvod blokace…" value={reason} onChange={e=>setReason(e.target.value)}/><div className="form-actions"><button className="ghost-button" onClick={()=>setBan(null)}>ZRUŠIT</button><button className="danger-button" onClick={()=>banUser('ban',ban)}>🚫 ZABLOKOVAT</button></div></div></div>}
 {del&&<div className="modal-bg"><div className="confirm-card"><div className="kicker">⚠ SMAZAT MARKER</div><h2>{del.name}</h2><p>Marker bude odstraněn z mapy. Tuto akci nelze vrátit.</p><div className="form-actions"><button className="ghost-button" onClick={()=>setDel(null)}>ZRUŠIT</button><button className="danger-button" onClick={async()=>{setBusy(true);await fetch(`/api/admin/markers/${del.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete',deleteImage:true})});setDel(null);await load();setBusy(false)}}>🗑 SMAZAT + FOTKU</button></div></div></div>}</div>}
