"use client";
import { useEffect,useMemo,useState } from "react";
import type { Marker } from "@/lib/types";
import { useLanguage } from "./LanguageProvider";
import LanguageSwitcher from "./LanguageSwitcher";
export default function AdminDashboard(){
 const {t}=useLanguage();const [markers,setMarkers]=useState<(Marker&{submitter_email?:string})[]>([]);const [filter,setFilter]=useState("pending");const [busy,setBusy]=useState<number|null>(null);
 async function load(){const r=await fetch("/api/admin/markers",{cache:"no-store"});if(r.ok)setMarkers(await r.json())}useEffect(()=>{load()},[]);
 const shown=useMemo(()=>filter==="all"?markers:markers.filter(m=>m.approval_status===filter),[markers,filter]);const pending=markers.filter(m=>m.approval_status==="pending").length,approved=markers.filter(m=>m.approval_status==="approved").length,rejected=markers.filter(m=>m.approval_status==="rejected").length;
 async function action(id:number,action:"approve"|"reject"|"delete"){if(action==="delete"&&!confirm(t("admin.confirmDelete")))return;setBusy(id);await fetch(`/api/admin/markers/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})});await load();setBusy(null)}
 return <div className="admin-page"><div className="admin-top"><div><div className="kicker">{t("admin.kicker")}</div><h1>{t("admin.title")}</h1></div><div className="admin-top-actions"><LanguageSwitcher/><a className="ghost-button" href="/">{t("common.backMap")}</a></div></div><div className="stats"><div><span>{t("admin.pending")}</span><b>{pending}</b></div><div><span>{t("admin.approved")}</span><b>{approved}</b></div><div><span>{t("admin.rejected")}</span><b>{rejected}</b></div><div><span>{t("admin.all")}</span><b>{markers.length}</b></div></div><div className="admin-tabs">{["pending","approved","rejected","all"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{t(`admin.tabs.${x}`)}</button>)}</div><div className="moderation-list">{shown.length===0&&<div className="empty">{t("admin.empty")}</div>}{shown.map(m=><article className="moderation-card" key={m.id}><div className="moderation-main"><div className="marker-type">{t(`types.${m.type}`).toUpperCase()}</div><h3>{m.name}</h3><div className="moderation-meta">LAT {Number(m.lat).toFixed(2)} · LON {Number(m.lon).toFixed(2)} · {m.submitter_name||m.submitter_email||t("admin.unknown")}</div><p>{m.note||t("common.noNote")}</p>{m.image_url&&<a href={m.image_url} target="_blank" rel="noreferrer"><img className="moderation-photo" src={m.image_url} alt={`${t("map.photoAlt")} ${m.name}`}/></a>}</div><div className="moderation-actions">{m.approval_status!=="approved"&&<button className="approve" disabled={busy===m.id} onClick={()=>action(m.id,"approve")}>{t("admin.approve")}</button>}{m.approval_status!=="rejected"&&<button className="reject" disabled={busy===m.id} onClick={()=>action(m.id,"reject")}>{t("admin.reject")}</button>}<button className="delete" disabled={busy===m.id} onClick={()=>action(m.id,"delete")}>{t("admin.delete")}</button></div></article>)}</div></div>
}
