"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "cs" | "en";

const translations = {
  cs: {
    common:{login:"Přihlásit",register:"Registrace",logout:"Odhlásit",admin:"ADMINISTRACE",cancel:"ZRUŠIT",delete:"SMAZAT",backMap:"← Zpět na mapu",noNote:"Bez poznámky."},
    header:{map:"INTERAKTIVNÍ MAPA SUROVIN",language:"Jazyk",server:"ARKSURVIVAL.CZ SERVER"},
    map:{filters:"FILTRY MAPY",clear:"VYMAZAT",farming:"⚡ DŮLEŽITÉ PRO FARMENÍ",resources:"ZDROJE",locations:"LOKACE",help:"Registrovaní uživatelé mohou navrhovat nové lokace. Veřejné jsou až po schválení adminem.",reset:"RESET FILTRŮ",quick:"RYCHLÉ AKCE",legend:"LEGENDA",approvedMarker:"Schválený marker",pendingMarker:"Čeká na schválení",yourMarker:"Tvůj marker",fitMap:"Zobrazit celou mapu",search:"Hledat zdroje, tvory, jeskyně…",add:"＋ PŘIDAT MARKER",pick:"📍 Klikni na mapu a vyber umístění markeru",done:"HOTOVO",published:"MARKER PUBLIKOVÁN",verified:"✓ OVĚŘENO",openPhoto:"↗ OTEVŘÍT FOTKU",photoAlt:"Fotka lokace",proposedBy:"NAVRHL LOKACI",unknownProposer:"Neznámý uživatel"},
    types:{metal:"Kov",richmetal:"Bohatý kov",crystal:"Krystal",obsidian:"Obsidián",oil:"Olej",oilvein:"Ropná žíla",sulfur:"Síra",silica:"Křemičité perly",blackpearls:"Černé perly",element:"Elementový prach",redingot:"Červený ingot",diamondingot:"Diamond ingot",goldingot:"Zlatý ingot",cave:"Jeskyně",artifact:"Artefakty",boss:"Bossové",loot:"Jeskynní loot",base:"Místa pro základnu",creature:"Výskyt tvorů"},
    creatures:{search:"Hledat tvora…",all:"VŠICHNI",selected:"vybraní",creature:"TVOR",choose:"Vyber tvora…",required:"Vyber tvora."},
    authModal:{title:"Přidej lokaci do Tharat Map",text:"Pro přidávání markerů potřebuješ bezplatný účet.",login:"PŘIHLÁSIT SE",create:"VYTVOŘIT ÚČET"},
    marker:{new:"Nový marker",changePos:"ZMĚNIT POZICI",type:"TYP LOKACE *",name:"NÁZEV *",note:"POZNÁMKA",photo:"FOTKA LOKACE",optional:"VOLITELNÉ · JPG / PNG / WEBP · MAX 4 MB",drop:"Přetáhni fotku sem",choose:"nebo klikni a vyber soubor",change:"ZMĚNIT",remove:"ODSTRANIT",uploading:"Nahrávám fotku…",adminPublish:"ADMIN PUBLIKACE",publishNow:"Publikovat okamžitě",moderation:"ⓘ Marker před zveřejněním zkontroluje administrátor.",sending:"ODESÍLÁM…",publish:"PUBLIKOVAT MARKER",submit:"ODESLAT MARKER",nameShort:"Název musí mít alespoň 2 znaky.",noteLong:"Maximum je 1000 znaků.",imageType:"Povolené jsou pouze JPG, PNG a WebP.",imageSize:"Fotka může mít maximálně 4 MB.",saveFail:"Fotografii nebo marker se nepodařilo uložit. Zkus to znovu.",saved:"Lokace byla odeslána administrátorovi ke schválení.",live:"Marker je nyní viditelný na veřejné mapě.",discardKicker:"NEULOŽENÉ ZMĚNY",discardTitle:"Zahodit rozepsaný marker?",discardText:"Rozepsané údaje budou ztraceny.",continueEdit:"POKRAČOVAT V ÚPRAVĚ",discard:"ZAHODIT"},
    login:{title:"Přihlášení",text:"Přihlas se, pokud chceš navrhovat nové lokace do mapy.",password:"HESLO",submit:"PŘIHLÁSIT",busy:"Přihlašuji…",invalid:"Neplatný e-mail nebo heslo.",noAccount:"Nemáš účet?",signup:"Zaregistrovat se"},
    register:{title:"Registrace",text:"Účet dostane roli user. Admin práva se nepřidělují registrací.",name:"JMÉNO",password:"HESLO",submit:"VYTVOŘIT ÚČET",busy:"Vytvářím účet…",fail:"Registrace selhala.",hasAccount:"Už účet máš?",login:"Přihlásit se"},
    detail:{searchPlaceholder:"Hledat lokaci, tvora nebo 53 67…",verifiedAdmin:"✓ OVĚŘENO ADMINEM",community:"✓ KOMUNITA",info:"Informace",comments:"Komentáře",gallery:"Galerie",creatureSpawn:"VÝSKYT TVORA",proposed:"NAVRHL",confirm:"✓ Potvrdit lokaci",deletedUser:"Smazaný uživatel",commentPlaceholder:"Napiš zkušenost s touto lokací…",send:"ODESLAT",loginComment:"Přihlas se pro komentář",noPhoto:"K této lokaci zatím není fotografie.",favorite:"Přidat do oblíbených",favorited:"V oblíbených",visited:"Navštíveno",markVisited:"Označit jako navštívené",share:"Sdílet",report:"Nahlásit lokaci",badCoords:"Špatné souřadnice",gone:"Lokace už neexistuje",duplicate:"Duplikát",badType:"Špatný typ",other:"Jiné",thanks:"Díky, hlášení bylo odesláno adminům.",latitude:"LATITUDE",longitude:"LONGITUDE",selectedMarker:"VYBRANÝ MARKER"},
    ranks:{title:"HODNOST PŘISPĚVATELE",approvedLocations:"schválených lokací",next:"Další hodnost",remaining:"zbývá {count} lokací",max:"Nejvyšší hodnost dosažena 👑",novice:"Nováček",explorer:"Průzkumník",hunter:"Lovec",cartographer:"Kartograf",expert:"Expert Tharatu",legend:"Legenda Tharatu"},
    profile:{back:"← ZPĚT NA MAPU",kicker:"THARAT SURVIVOR PROFILE",image:"PROFILOVÝ OBRÁZEK",avatar:"Avatar / GIF",imageHelp:"Nahraj JPG, PNG, WebP nebo animovaný GIF. Maximálně 4 MB.",upload:"NAHRÁT OBRÁZEK / GIF",uploading:"NAHRÁVÁM…",remove:"ODSTRANIT",favoritesKicker:"⭐ OBLÍBENÉ LOKACE",favorites:"Oblíbené",noFavorites:"Zatím žádné oblíbené lokace.",visitedKicker:"✓ NAVŠTÍVENÉ",visited:"Navštívené",noVisited:"Zatím žádné navštívené lokace.",contribKicker:"🗺 MOJE PŘÍSPĚVKY",contrib:"Moje lokace",noContrib:"Zatím jsi žádnou lokaci nenavrhl.",security:"ZABEZPEČENÍ",changePassword:"Změnit heslo",passwordHelp:"Pro potvrzení změny zadej nejdřív své současné heslo.",currentPassword:"SOUČASNÉ HESLO",newPassword:"NOVÉ HESLO",newPasswordAgain:"NOVÉ HESLO ZNOVU",danger:"NEBEZPEČNÁ ZÓNA",deleteAccount:"Smazat účet",deleteHelp:"Smazání je nevratné. Tvé markery zůstanou v mapě anonymně, ale účet a profil budou odstraněny.",delete:"SMAZAT ÚČET",passwordConfirm:"HESLO PRO POTVRZENÍ",deleteForever:"TRVALE SMAZAT ÚČET",adminStyle:"ADMIN VZHLED",adminFrame:"Animovaný admin rámeček",adminFrameHelp:"Exkluzivní animovaný rámeček kolem tvého avataru. Zobrazuje se na profilu a u autora lokace v detailu markeru.",adminFrameOn:"RÁMEČEK ZAPNUTÝ",adminFrameOff:"ZAPNOUT RÁMEČEK",adminFrameEnabled:"Admin rámeček byl zapnut.",adminFrameDisabled:"Admin rámeček byl vypnut.",adminFrameError:"Rámeček se nepodařilo změnit.",baseKicker:"MOJE ZÁKLADNA",baseTitle:"Pozice základny",baseHelp:"Ulož si LAT a LON své základny. Pozice je soukromá a na mapě ji vidíš pouze ty.",baseLat:"LAT",baseLon:"LON",baseSave:"ULOŽIT ZÁKLADNU",baseRemove:"ODSTRANIT POZICI",baseSaved:"Pozice základny byla uložena.",baseRemoved:"Pozice základny byla odstraněna.",baseError:"Pozici základny se nepodařilo uložit.",myBase:"MOJE ZÁKLADNA"},
    leaderboard:{back:"ZPĚT NA MAPU",title:"Žebříček komunity",subtitle:"Nejaktivnější průzkumníci Tharatu podle počtu schválených lokací.",player:"HRÁČ",rank:"HODNOST",locations:"SCHVÁLENÉ LOKACE"},
    notifications:{title:"UPOZORNĚNÍ",empty:"Zatím žádná upozornění.",readAll:"OZNAČIT VŠE JAKO PŘEČTENÉ",clear:"VYMAZAT",approved:"Tvoje lokace „{name}“ byla schválena.",rejected:"Tvoje lokace „{name}“ byla zamítnuta.",comment_reply:"{name} odpověděl(a) na tvůj komentář."},
    comments:{reply:"ODPOVĚDĚT",edit:"UPRAVIT",delete:"SMAZAT",hide:"SKRÝT",save:"ULOŽIT",edited:"upraveno",replyingTo:"Odpovídáš uživateli",sendReply:"ODESLAT ODPOVĚĎ",deleteConfirm:"Opravdu chceš tento komentář odstranit?"},
    featured:{badge:"DOPORUČENO"},
    mobile:{filters:"FILTRY",close:"Zavřít filtry"},
    reports:{outdated:"Neaktuální lokace",badCoords:"Špatné souřadnice",gone:"Lokace už neexistuje",duplicate:"Duplikát",badType:"Špatný typ",other:"Jiné",detail:"Doplňující informace (volitelné)",send:"ODESLAT HLÁŠENÍ"},
    admin:{kicker:"THARAT CONTROL CENTER",title:"Admin Dashboard",pending:"ČEKAJÍCÍ",approved:"SCHVÁLENÉ",rejected:"ZAMÍTNUTÉ",all:"CELKEM",empty:"V této kategorii zatím nic není.",unknown:"neznámý uživatel",approve:"✓ SCHVÁLIT",reject:"✕ ZAMÍTNOUT",delete:"SMAZAT",confirmDelete:"Opravdu marker smazat?",tabs:{pending:"ČEKAJÍCÍ",approved:"SCHVÁLENÉ",rejected:"ZAMÍTNUTÉ",all:"VŠE"}}
  },
  en: {
    common:{login:"Log in",register:"Register",logout:"Log out",admin:"ADMINISTRATION",cancel:"CANCEL",delete:"DELETE",backMap:"← Back to map",noNote:"No notes."},
    header:{map:"INTERACTIVE RESOURCE MAP",language:"Language",server:"ARKSURVIVAL.CZ SERVER"},
    map:{filters:"MAP FILTERS",clear:"CLEAR",farming:"⚡ FARMING ESSENTIALS",resources:"RESOURCES",locations:"LOCATIONS",help:"Registered users can suggest new locations. They become public after admin approval.",reset:"RESET FILTERS",quick:"QUICK ACTIONS",legend:"LEGEND",approvedMarker:"Approved marker",pendingMarker:"Pending approval",yourMarker:"Your marker",fitMap:"Fit full map",search:"Search resources, creatures, caves…",add:"＋ ADD MARKER",pick:"📍 Click the map to choose the marker location",done:"DONE",published:"MARKER PUBLISHED",verified:"✓ VERIFIED",openPhoto:"↗ OPEN PHOTO",photoAlt:"Location photo",proposedBy:"LOCATION PROPOSED BY",unknownProposer:"Unknown user"},
    types:{metal:"Metal",richmetal:"Rich Metal",crystal:"Crystal",obsidian:"Obsidian",oil:"Oil",oilvein:"Oil Vein",sulfur:"Sulfur",silica:"Silica Pearls",blackpearls:"Black Pearls",element:"Element Dust",redingot:"Red Ingot",diamondingot:"Diamond Ingot",goldingot:"Gold Ingot",cave:"Caves",artifact:"Artifacts",boss:"Bosses",loot:"Cave Loot",base:"Base Spots",creature:"Creature Spawn"},
    creatures:{search:"Search creatures…",all:"ALL",selected:"selected",creature:"CREATURE",choose:"Choose a creature…",required:"Choose a creature."},
    authModal:{title:"Add a location to Tharat Map",text:"You need a free account to add markers.",login:"LOG IN",create:"CREATE ACCOUNT"},
    marker:{new:"New marker",changePos:"CHANGE POSITION",type:"LOCATION TYPE *",name:"NAME *",note:"NOTE",photo:"LOCATION PHOTO",optional:"OPTIONAL · JPG / PNG / WEBP · MAX 4 MB",drop:"Drop a photo here",choose:"or click to choose a file",change:"CHANGE",remove:"REMOVE",uploading:"Uploading photo…",adminPublish:"ADMIN PUBLISHING",publishNow:"Publish immediately",moderation:"ⓘ An administrator will review the marker before it becomes public.",sending:"SENDING…",publish:"PUBLISH MARKER",submit:"SUBMIT MARKER",nameShort:"Name must contain at least 2 characters.",noteLong:"Maximum length is 1000 characters.",imageType:"Only JPG, PNG and WebP are allowed.",imageSize:"The photo can be up to 4 MB.",saveFail:"The photo or marker could not be saved. Please try again.",saved:"The location was sent to an administrator for approval.",live:"The marker is now visible on the public map.",discardKicker:"UNSAVED CHANGES",discardTitle:"Discard this marker draft?",discardText:"Your unsaved information will be lost.",continueEdit:"CONTINUE EDITING",discard:"DISCARD"},
    login:{title:"Log in",text:"Log in if you want to suggest new locations for the map.",password:"PASSWORD",submit:"LOG IN",busy:"Logging in…",invalid:"Invalid email or password.",noAccount:"Don't have an account?",signup:"Register"},
    register:{title:"Register",text:"The account will receive the user role. Admin rights cannot be obtained through registration.",name:"NAME",password:"PASSWORD",submit:"CREATE ACCOUNT",busy:"Creating account…",fail:"Registration failed.",hasAccount:"Already have an account?",login:"Log in"},
    detail:{searchPlaceholder:"Search location, creature or 53 67…",verifiedAdmin:"✓ VERIFIED BY ADMIN",community:"✓ COMMUNITY",info:"Information",comments:"Comments",gallery:"Gallery",creatureSpawn:"CREATURE SPAWN",proposed:"PROPOSED BY",confirm:"✓ Confirm location",deletedUser:"Deleted user",commentPlaceholder:"Share your experience with this location…",send:"SEND",loginComment:"Log in to comment",noPhoto:"There is no photo for this location yet.",favorite:"Add to favorites",favorited:"In favorites",visited:"Visited",markVisited:"Mark as visited",share:"Share",report:"Report location",badCoords:"Incorrect coordinates",gone:"Location no longer exists",duplicate:"Duplicate",badType:"Wrong type",other:"Other",thanks:"Thanks, the report was sent to the admins.",latitude:"LATITUDE",longitude:"LONGITUDE",selectedMarker:"SELECTED MARKER"},
    ranks:{title:"CONTRIBUTOR RANK",approvedLocations:"approved locations",next:"Next rank",remaining:"{count} locations remaining",max:"Highest rank reached 👑",novice:"Newcomer",explorer:"Explorer",hunter:"Hunter",cartographer:"Cartographer",expert:"Tharat Expert",legend:"Tharat Legend"},
    profile:{back:"← BACK TO MAP",kicker:"THARAT SURVIVOR PROFILE",image:"PROFILE IMAGE",avatar:"Avatar / GIF",imageHelp:"Upload JPG, PNG, WebP or an animated GIF. Maximum 4 MB.",upload:"UPLOAD IMAGE / GIF",uploading:"UPLOADING…",remove:"REMOVE",favoritesKicker:"⭐ FAVORITE LOCATIONS",favorites:"Favorites",noFavorites:"No favorite locations yet.",visitedKicker:"✓ VISITED",visited:"Visited",noVisited:"No visited locations yet.",contribKicker:"🗺 MY CONTRIBUTIONS",contrib:"My locations",noContrib:"You haven't proposed any locations yet.",security:"SECURITY",changePassword:"Change password",passwordHelp:"Enter your current password first to confirm the change.",currentPassword:"CURRENT PASSWORD",newPassword:"NEW PASSWORD",newPasswordAgain:"NEW PASSWORD AGAIN",danger:"DANGER ZONE",deleteAccount:"Delete account",deleteHelp:"Deletion is permanent. Your markers will remain on the map anonymously, but your account and profile will be removed.",delete:"DELETE ACCOUNT",passwordConfirm:"PASSWORD TO CONFIRM",deleteForever:"PERMANENTLY DELETE ACCOUNT",adminStyle:"ADMIN APPEARANCE",adminFrame:"Animated admin frame",adminFrameHelp:"An exclusive animated frame around your avatar. It appears on your profile and around the location author in marker details.",adminFrameOn:"FRAME ENABLED",adminFrameOff:"ENABLE FRAME",adminFrameEnabled:"Admin frame enabled.",adminFrameDisabled:"Admin frame disabled.",adminFrameError:"Could not change the frame.",baseKicker:"MY BASE",baseTitle:"Base location",baseHelp:"Save the LAT and LON of your base. The position is private and only visible to you on the map.",baseLat:"LAT",baseLon:"LON",baseSave:"SAVE BASE",baseRemove:"REMOVE LOCATION",baseSaved:"Base location saved.",baseRemoved:"Base location removed.",baseError:"Could not save base location.",myBase:"MY BASE"},
    leaderboard:{back:"BACK TO MAP",title:"Community Leaderboard",subtitle:"Tharat’s most active explorers ranked by approved locations.",player:"PLAYER",rank:"RANK",locations:"APPROVED LOCATIONS"},
    notifications:{title:"NOTIFICATIONS",empty:"No notifications yet.",readAll:"MARK ALL AS READ",clear:"CLEAR",approved:"Your location “{name}” was approved.",rejected:"Your location “{name}” was rejected.",comment_reply:"{name} replied to your comment."},
    comments:{reply:"REPLY",edit:"EDIT",delete:"DELETE",hide:"HIDE",save:"SAVE",edited:"edited",replyingTo:"Replying to",sendReply:"SEND REPLY",deleteConfirm:"Are you sure you want to remove this comment?"},
    featured:{badge:"FEATURED"},
    mobile:{filters:"FILTERS",close:"Close filters"},
    reports:{outdated:"Outdated location",badCoords:"Incorrect coordinates",gone:"Location no longer exists",duplicate:"Duplicate",badType:"Wrong type",other:"Other",detail:"Additional information (optional)",send:"SEND REPORT"},
    admin:{kicker:"THARAT CONTROL CENTER",title:"Admin Dashboard",pending:"PENDING",approved:"APPROVED",rejected:"REJECTED",all:"TOTAL",empty:"There is nothing in this category yet.",unknown:"unknown user",approve:"✓ APPROVE",reject:"✕ REJECT",delete:"DELETE",confirmDelete:"Are you sure you want to delete this marker?",tabs:{pending:"PENDING",approved:"APPROVED",rejected:"REJECTED",all:"ALL"}}
  }
} as const;

type Ctx = { language:Language; setLanguage:(l:Language)=>void; t:(path:string)=>string };
const LanguageContext=createContext<Ctx|null>(null);
function lookup(obj:any,path:string){return path.split(".").reduce((a,k)=>a?.[k],obj) ?? path}

export function LanguageProvider({children}:{children:React.ReactNode}){
  const [language,setLanguageState]=useState<Language>("cs");
  useEffect(()=>{const saved=localStorage.getItem("tharat-language");if(saved==="cs"||saved==="en")setLanguageState(saved)},[]);
  const setLanguage=(l:Language)=>{setLanguageState(l);localStorage.setItem("tharat-language",l);document.documentElement.lang=l};
  useEffect(()=>{document.documentElement.lang=language},[language]);
  const value=useMemo(()=>({language,setLanguage,t:(path:string)=>String(lookup(translations[language],path))}),[language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function useLanguage(){const c=useContext(LanguageContext);if(!c)throw new Error("useLanguage must be inside LanguageProvider");return c}
