"use client";
import { useRef,useState } from "react";
import { signOut } from "next-auth/react";
export default function ProfileClient({user}:{user:any}){
 const [avatar,setAvatar]=useState(user.avatar_url||""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const [currentPassword,setCurrent]=useState(""); const [newPassword,setNew]=useState(""); const [confirmPassword,setConfirm]=useState(""); const [deletePassword,setDeletePassword]=useState(""); const [danger,setDanger]=useState(false);
 async function upload(file?:File){if(!file)return;setMsg("");setBusy(true);const fd=new FormData();fd.append("file",file);const r=await fetch("/api/profile/avatar",{method:"POST",body:fd});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Nahrání selhalo.");setAvatar(d.url);setMsg("Profilový obrázek byl změněn.");}
 async function removeAvatar(){setBusy(true);const r=await fetch("/api/profile/avatar",{method:"DELETE"});setBusy(false);if(r.ok){setAvatar("");setMsg("Profilový obrázek byl odstraněn.");}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setMsg("");if(newPassword!==confirmPassword)return setMsg("Nová hesla se neshodují.");setBusy(true);const r=await fetch("/api/profile/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Změna hesla selhala.");setCurrent("");setNew("");setConfirm("");setMsg("Heslo bylo úspěšně změněno.");}
 async function deleteAccount(){if(!deletePassword)return setMsg("Pro smazání účtu zadej heslo.");setBusy(true);const r=await fetch("/api/profile/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:deletePassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Účet se nepodařilo smazat.");await signOut({callbackUrl:"/"});}
 return <main className="profile-page"><a href="/" className="profile-back">← ZPĚT NA MAPU</a><div className="profile-head"><div className="profile-avatar">{avatar?<img src={avatar} alt="Profil"/>:<span>{(user.name||user.email||"U").slice(0,1).toUpperCase()}</span>}</div><div><small>THARAT SURVIVOR PROFILE</small><h1>{user.name}</h1><p>{user.email}</p><em>{user.role}</em></div></div>{msg&&<div className="profile-message">{msg}</div>}
 <section className="profile-card"><div><small>PROFILOVÝ OBRÁZEK</small><h2>Avatar / GIF</h2><p>Nahraj JPG, PNG, WebP nebo animovaný GIF. Maximálně 4 MB.</p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden onChange={e=>upload(e.target.files?.[0])}/><div className="profile-actions"><button className="accent-button" disabled={busy} onClick={()=>fileRef.current?.click()}>{busy?"NAHRÁVÁM…":"NAHRÁT OBRÁZEK / GIF"}</button>{avatar&&<button className="ghost-button" disabled={busy} onClick={removeAvatar}>ODSTRANIT</button>}</div></section>
 <section className="profile-card"><div><small>ZABEZPEČENÍ</small><h2>Změnit heslo</h2><p>Pro potvrzení změny zadej nejdřív své současné heslo.</p></div><form className="profile-form" onSubmit={changePassword}><label>SOUČASNÉ HESLO<input type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required minLength={8}/></label><label>NOVÉ HESLO<input type="password" value={newPassword} onChange={e=>setNew(e.target.value)} required minLength={8}/></label><label>NOVÉ HESLO ZNOVU<input type="password" value={confirmPassword} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label><button className="accent-button" disabled={busy}>ZMĚNIT HESLO</button></form></section>
 <section className="profile-card danger-zone"><div><small>NEBEZPEČNÁ ZÓNA</small><h2>Smazat účet</h2><p>Smazání je nevratné. Tvé markery zůstanou v mapě anonymně, ale účet a profil budou odstraněny.</p></div>{!danger?<button className="danger-button" onClick={()=>setDanger(true)}>SMAZAT ÚČET</button>:<div className="delete-confirm"><label>HESLO PRO POTVRZENÍ<input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/></label><div><button className="ghost-button" onClick={()=>setDanger(false)}>ZRUŠIT</button><button className="danger-button" disabled={busy} onClick={deleteAccount}>TRVALE SMAZAT ÚČET</button></div></div>}</section></main>
}
