"use client";
import { useEffect,useRef,useState } from "react";
import { signOut } from "next-auth/react";
import { useLanguage } from "./LanguageProvider";
import { contributorRank } from "@/lib/ranks";
export default function ProfileClient({user}:{user:any}){
 const {t}=useLanguage();
 const rankName=(r:any)=>t(`ranks.${r.key}`);
 const remainingText=(n:number)=>t("ranks.remaining").replace("{count}",String(n));
 const rank=contributorRank(user.approved_count||0);
 const [avatar,setAvatar]=useState(user.avatar_url||""); const [adminFrame,setAdminFrame]=useState(Boolean(user.admin_frame_enabled)); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const [activity,setActivity]=useState<any>({favorites:[],visited:[],contributions:[]}); const [expanded,setExpanded]=useState<Record<string,boolean>>({favorites:false,visited:false,contributions:false}); useEffect(()=>{fetch("/api/profile/activity").then(r=>r.ok?r.json():null).then(d=>d&&setActivity(d)).catch(()=>{})},[]);
 const [baseLat,setBaseLat]=useState(user.base_lat==null?"":String(user.base_lat)); const [baseLon,setBaseLon]=useState(user.base_lon==null?"":String(user.base_lon));
 const [currentPassword,setCurrent]=useState(""); const [newPassword,setNew]=useState(""); const [confirmPassword,setConfirm]=useState(""); const [deletePassword,setDeletePassword]=useState(""); const [danger,setDanger]=useState(false);
 async function upload(file?:File){if(!file)return;setMsg("");setBusy(true);const fd=new FormData();fd.append("file",file);const r=await fetch("/api/profile/avatar",{method:"POST",body:fd});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Nahrání selhalo.");setAvatar(d.url);setMsg("Profilový obrázek byl změněn.");}
 async function removeAvatar(){setBusy(true);const r=await fetch("/api/profile/avatar",{method:"DELETE"});setBusy(false);if(r.ok){setAvatar("");setMsg("Profilový obrázek byl odstraněn.");}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setMsg("");if(newPassword!==confirmPassword)return setMsg("Nová hesla se neshodují.");setBusy(true);const r=await fetch("/api/profile/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Změna hesla selhala.");setCurrent("");setNew("");setConfirm("");setMsg("Heslo bylo úspěšně změněno.");}
 async function toggleAdminFrame(){setBusy(true);const next=!adminFrame;const r=await fetch("/api/profile/frame",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:next})});setBusy(false);if(r.ok){setAdminFrame(next);setMsg(next?t("profile.adminFrameEnabled"):t("profile.adminFrameDisabled"));}else setMsg(t("profile.adminFrameError"));}
 async function saveBase(remove=false){setBusy(true);const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({base_lat:remove?null:baseLat,base_lon:remove?null:baseLon})});setBusy(false);if(r.ok){if(remove){setBaseLat("");setBaseLon("");setMsg(t("profile.baseRemoved"));}else setMsg(t("profile.baseSaved"));}else setMsg(t("profile.baseError"));}
 async function deleteAccount(){if(!deletePassword)return setMsg("Pro smazání účtu zadej heslo.");setBusy(true);const r=await fetch("/api/profile/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:deletePassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Účet se nepodařilo smazat.");await signOut({callbackUrl:"/"});}
 return <main className="profile-page"><a href="/" className="profile-back">{t("profile.back")}</a><div className="profile-head"><div className={`profile-avatar ${user.role==="admin"&&adminFrame?"admin-animated-frame":""}`}>{avatar?<img src={avatar} alt="Profil"/>:<span>{(user.name||user.email||"U").slice(0,1).toUpperCase()}</span>}</div><div><small>{t("profile.kicker")}</small><h1>{user.name}</h1><p>{user.email}</p><div className="profile-badges"><em>{user.role}</em><span className="rank-badge">{rank.rank.icon} {rankName(rank.rank)}</span></div></div></div><section className="rank-progress-card"><div><small>{t("ranks.title")}</small><b>{rank.rank.icon} {rankName(rank.rank)}</b><span>{rank.count} {t("ranks.approvedLocations")}</span></div><div className="rank-progress-wrap"><div className="rank-progress-track"><i style={{width:`${rank.progress}%`}}/></div>{rank.next?<p>{t("ranks.next")}: <strong>{rank.next.icon} {rankName(rank.next)}</strong> · {remainingText(rank.remaining)}</p>:<p>{t("ranks.max")}</p>}</div></section>{msg&&<div className="profile-message">{msg}</div>}
 <section className="profile-card"><div><small>{t("profile.image")}</small><h2>{t("profile.avatar")}</h2><p>{t("profile.imageHelp")}</p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden onChange={e=>upload(e.target.files?.[0])}/><div className="profile-actions"><button className="accent-button" disabled={busy} onClick={()=>fileRef.current?.click()}>{busy?t("profile.uploading"):t("profile.upload")}</button>{avatar&&<button className="ghost-button" disabled={busy} onClick={removeAvatar}>{t("profile.remove")}</button>}</div></section>
 {user.role==="admin"&&<section className="profile-card admin-frame-settings"><div><small>{t("profile.adminStyle")}</small><h2>{t("profile.adminFrame")}</h2><p>{t("profile.adminFrameHelp")}</p></div><div className="admin-frame-control"><div className={`admin-frame-preview ${adminFrame?"admin-animated-frame":""}`}>{avatar?<img src={avatar} alt=""/>:<span>{(user.name||"A").slice(0,1).toUpperCase()}</span>}</div><button className={adminFrame?"accent-button":"ghost-button"} disabled={busy} onClick={toggleAdminFrame}>{adminFrame?t("profile.adminFrameOn"):t("profile.adminFrameOff")}</button></div></section>}

 <section className="profile-card profile-base-card"><div><small>{t("profile.baseKicker")}</small><h2>{t("profile.baseTitle")}</h2><p>{t("profile.baseHelp")}</p></div><div className="base-location-form"><label>{t("profile.baseLat")}<input type="number" min="0" max="100" step="0.01" value={baseLat} onChange={e=>setBaseLat(e.target.value)}/></label><label>{t("profile.baseLon")}<input type="number" min="0" max="100" step="0.01" value={baseLon} onChange={e=>setBaseLon(e.target.value)}/></label><button className="accent-button" disabled={busy||baseLat===""||baseLon===""} onClick={()=>saveBase(false)}>{t("profile.baseSave")}</button>{(baseLat!==""||baseLon!=="")&&<button className="ghost-button" disabled={busy} onClick={()=>saveBase(true)}>{t("profile.baseRemove")}</button>}</div></section>
 <section className="profile-community">{[
  {key:"favorites",kicker:t("profile.favoritesKicker"),title:t("profile.favorites"),empty:t("profile.noFavorites")},
  {key:"visited",kicker:t("profile.visitedKicker"),title:t("profile.visited"),empty:t("profile.noVisited")},
  {key:"contributions",kicker:t("profile.contribKicker"),title:t("profile.contrib"),empty:t("profile.noContrib")}
 ].map((section:any)=>{const items=activity[section.key]||[];const shown=expanded[section.key]?items:items.slice(0,5);return <div className="profile-community-col" key={section.key}><small>{section.kicker}</small><h2>{section.title}</h2>{shown.length?shown.map((m:any)=><a key={m.id} href={`/?marker=${m.id}`}>{m.name}<span>{section.key==='contributions'?m.approval_status:`LAT ${Number(m.lat).toFixed(1)} / LON ${Number(m.lon).toFixed(1)}`}</span></a>):<p>{section.empty}</p>}{items.length>5&&<button className="profile-show-all" onClick={()=>setExpanded(v=>({...v,[section.key]:!v[section.key]}))}>{expanded[section.key]?"▲ ZOBRAZIT MÉNĚ":`ZOBRAZIT VŠE (${items.length})`}</button>}</div>})}</section>
 <section className="profile-settings-grid"><section className="profile-card profile-card-stack"><div><small>{t("profile.security")}</small><h2>{t("profile.changePassword")}</h2><p>{t("profile.passwordHelp")}</p></div><form className="profile-form" onSubmit={changePassword}><label>{t("profile.currentPassword")}<input type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required minLength={8}/></label><label>{t("profile.newPassword")}<input type="password" value={newPassword} onChange={e=>setNew(e.target.value)} required minLength={8}/></label><label>{t("profile.newPasswordAgain")}<input type="password" value={confirmPassword} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label><button className="accent-button" disabled={busy}>{t("profile.changePassword")}</button></form></section>
 <section className="profile-card profile-card-stack danger-zone"><div><small>{t("profile.danger")}</small><h2>{t("profile.deleteAccount")}</h2><p>{t("profile.deleteHelp")}</p></div>{!danger?<button className="danger-button" onClick={()=>setDanger(true)}>{t("profile.delete")}</button>:<div className="delete-confirm"><label>{t("profile.passwordConfirm")}<input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/></label><div><button className="ghost-button" onClick={()=>setDanger(false)}>{t("common.cancel")}</button><button className="danger-button" disabled={busy} onClick={deleteAccount}>{t("profile.deleteForever")}</button></div></div>}</section></section></main>
}