"use client";
import { useEffect,useRef,useState } from "react";
import { signOut } from "next-auth/react";
import { useLanguage } from "./LanguageProvider";
export default function ProfileClient({user}:{user:any}){
 const {t}=useLanguage();
 const [avatar,setAvatar]=useState(user.avatar_url||""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const [activity,setActivity]=useState<any>({favorites:[],visited:[],contributions:[]}); useEffect(()=>{fetch("/api/profile/activity").then(r=>r.ok?r.json():null).then(d=>d&&setActivity(d)).catch(()=>{})},[]);
 const [currentPassword,setCurrent]=useState(""); const [newPassword,setNew]=useState(""); const [confirmPassword,setConfirm]=useState(""); const [deletePassword,setDeletePassword]=useState(""); const [danger,setDanger]=useState(false);
 async function upload(file?:File){if(!file)return;setMsg("");setBusy(true);const fd=new FormData();fd.append("file",file);const r=await fetch("/api/profile/avatar",{method:"POST",body:fd});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Nahrání selhalo.");setAvatar(d.url);setMsg("Profilový obrázek byl změněn.");}
 async function removeAvatar(){setBusy(true);const r=await fetch("/api/profile/avatar",{method:"DELETE"});setBusy(false);if(r.ok){setAvatar("");setMsg("Profilový obrázek byl odstraněn.");}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setMsg("");if(newPassword!==confirmPassword)return setMsg("Nová hesla se neshodují.");setBusy(true);const r=await fetch("/api/profile/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Změna hesla selhala.");setCurrent("");setNew("");setConfirm("");setMsg("Heslo bylo úspěšně změněno.");}
 async function deleteAccount(){if(!deletePassword)return setMsg("Pro smazání účtu zadej heslo.");setBusy(true);const r=await fetch("/api/profile/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:deletePassword})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error||"Účet se nepodařilo smazat.");await signOut({callbackUrl:"/"});}
 return <main className="profile-page"><a href="/" className="profile-back">{t("profile.back")}</a><div className="profile-head"><div className="profile-avatar">{avatar?<img src={avatar} alt="Profil"/>:<span>{(user.name||user.email||"U").slice(0,1).toUpperCase()}</span>}</div><div><small>{t("profile.kicker")}</small><h1>{user.name}</h1><p>{user.email}</p><em>{user.role}</em></div></div>{msg&&<div className="profile-message">{msg}</div>}
 <section className="profile-card"><div><small>{t("profile.image")}</small><h2>{t("profile.avatar")}</h2><p>{t("profile.imageHelp")}</p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden onChange={e=>upload(e.target.files?.[0])}/><div className="profile-actions"><button className="accent-button" disabled={busy} onClick={()=>fileRef.current?.click()}>{busy?t("profile.uploading"):t("profile.upload")}</button>{avatar&&<button className="ghost-button" disabled={busy} onClick={removeAvatar}>{t("profile.remove")}</button>}</div></section>
 <section className="profile-community"><div className="profile-community-col"><small>{t("profile.favoritesKicker")}</small><h2>{t("profile.favorites")}</h2>{activity.favorites.length?activity.favorites.map((m:any)=><a key={m.id} href={`/?marker=${m.id}`}>{m.name}<span>LAT {Number(m.lat).toFixed(1)} / LON {Number(m.lon).toFixed(1)}</span></a>):<p>{t("profile.noFavorites")}</p>}</div><div className="profile-community-col"><small>{t("profile.visitedKicker")}</small><h2>{t("profile.visited")}</h2>{activity.visited.length?activity.visited.map((m:any)=><a key={m.id} href={`/?marker=${m.id}`}>{m.name}<span>LAT {Number(m.lat).toFixed(1)} / LON {Number(m.lon).toFixed(1)}</span></a>):<p>{t("profile.noVisited")}</p>}</div><div className="profile-community-col"><small>{t("profile.contribKicker")}</small><h2>{t("profile.contrib")}</h2>{activity.contributions.length?activity.contributions.map((m:any)=><a key={m.id} href={`/?marker=${m.id}`}>{m.name}<span>{m.approval_status}</span></a>):<p>{t("profile.noContrib")}</p>}</div></section>
 <section className="profile-settings-grid"><section className="profile-card profile-card-stack"><div><small>{t("profile.security")}</small><h2>{t("profile.changePassword")}</h2><p>{t("profile.passwordHelp")}</p></div><form className="profile-form" onSubmit={changePassword}><label>{t("profile.currentPassword")}<input type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required minLength={8}/></label><label>{t("profile.newPassword")}<input type="password" value={newPassword} onChange={e=>setNew(e.target.value)} required minLength={8}/></label><label>{t("profile.newPasswordAgain")}<input type="password" value={confirmPassword} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label><button className="accent-button" disabled={busy}>{t("profile.changePassword")}</button></form></section>
 <section className="profile-card profile-card-stack danger-zone"><div><small>{t("profile.danger")}</small><h2>{t("profile.deleteAccount")}</h2><p>{t("profile.deleteHelp")}</p></div>{!danger?<button className="danger-button" onClick={()=>setDanger(true)}>{t("profile.delete")}</button>:<div className="delete-confirm"><label>{t("profile.passwordConfirm")}<input type="password" value={deletePassword} onChange={e=>setDeletePassword(e.target.value)}/></label><div><button className="ghost-button" onClick={()=>setDanger(false)}>{t("common.cancel")}</button><button className="danger-button" disabled={busy} onClick={deleteAccount}>{t("profile.deleteForever")}</button></div></div>}</section></section></main>
}