import { NextResponse } from 'next/server';import { auth } from '@/auth';import { sql } from '@/lib/db';import { z } from 'zod';import { del } from '@vercel/blob';
const schema=z.discriminatedUnion('action',[
 z.object({action:z.literal('approve')}),z.object({action:z.literal('reject')}),z.object({action:z.literal('delete'),deleteImage:z.boolean().optional()}),
 z.object({action:z.literal('update'),name:z.string().trim().min(2).max(100),type:z.string().min(1).max(30),lat:z.number().min(0).max(100),lon:z.number().min(0).max(100),note:z.string().max(1000),image_url:z.string().url().nullable(),approval_status:z.enum(['pending','approved','rejected']),featured:z.boolean().optional().default(false)})
]);
export async function PATCH(req:Request,ctx:{params:Promise<{id:string}>}){const session=await auth();if(!session?.user||!['admin','moderator'].includes(session.user.role))return NextResponse.json({error:'Forbidden'},{status:403});const adminId=session.user.id;const {id}=await ctx.params;const markerId=Number(id);if(!Number.isInteger(markerId))return NextResponse.json({error:'Bad id'},{status:400});const body=schema.parse(await req.json());const db=sql();const old=(await db`SELECT image_url,submitted_by,name FROM markers WHERE id=${markerId}`)[0] as any;if(!old)return NextResponse.json({error:'Not found'},{status:404});
 if(body.action==='delete'){await db`DELETE FROM markers WHERE id=${markerId}`;if(body.deleteImage&&old.image_url)try{await del(old.image_url)}catch(e){console.error(e)};await log('marker_deleted',{id:markerId});return NextResponse.json({ok:true})}
 if(body.action==='update'){const status=body.approval_status==='approved'?'verified':'unverified';await db`UPDATE markers SET name=${body.name},type=${body.type},lat=${body.lat},lon=${body.lon},note=${body.note},image_url=${body.image_url},approval_status=${body.approval_status},featured=${body.featured},status=${status},reviewed_by=${adminId},reviewed_at=now(),updated_at=now() WHERE id=${markerId}`;if(old.image_url&&old.image_url!==body.image_url)try{await del(old.image_url)}catch(e){console.error(e)};await log('marker_updated',{id:markerId});return NextResponse.json({ok:true})}
 const approval=body.action==='approve'?'approved':'rejected',status=body.action==='approve'?'verified':'unverified';await db`UPDATE markers SET approval_status=${approval},status=${status},reviewed_by=${adminId},reviewed_at=now(),updated_at=now() WHERE id=${markerId}`;await log(body.action==='approve'?'marker_approved':'marker_rejected',{id:markerId});if(old.submitted_by){const txt=body.action==='approve'?`Tvoje lokace „${old.name}“ byla schválena.`:`Tvoje lokace „${old.name}“ byla zamítnuta.`;try{const nk=body.action==='approve'?'approved':'rejected';await db`INSERT INTO notifications(user_id,text,href,notification_key,data_json) VALUES(${old.submitted_by},${txt},${body.action==='approve'?`/?marker=${markerId}`:'/profile'},${nk},${JSON.stringify({name:old.name})}::jsonb)`}catch(e){console.error('notification',e)}}return NextResponse.json({ok:true});
 async function log(action:string,details:any){await db`INSERT INTO admin_actions(admin_id,action,target_type,target_id,details) VALUES(${adminId},${action},'marker',${String(markerId)},${JSON.stringify(details)}::jsonb)`}
}
