-- THARAT Admin Panel V2 migration - run once in Neon Query editor.
-- If your editor only accepts one prepared statement at a time, run each ALTER/CREATE separately.
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_reason TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE markers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE TABLE IF NOT EXISTS admin_actions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,admin_id UUID REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(60) NOT NULL,target_type VARCHAR(30) NOT NULL,target_id TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS admin_actions_created_idx ON admin_actions(created_at DESC);
CREATE INDEX IF NOT EXISTS users_banned_idx ON users(banned);
