import { neon } from "@neondatabase/serverless";

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL missing");
const sql = neon(process.env.DATABASE_URL);

await sql`
CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(40) NOT NULL,
  email varchar(254) NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role varchar(10) NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
  created_at timestamptz NOT NULL DEFAULT now()
)`;

await sql`
CREATE TABLE IF NOT EXISTS markers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type varchar(30) NOT NULL,
  name varchar(100) NOT NULL,
  lat numeric(5,2) NOT NULL CHECK (lat BETWEEN 0 AND 100),
  lon numeric(5,2) NOT NULL CHECK (lon BETWEEN 0 AND 100),
  note varchar(1000) NOT NULL DEFAULT '',
  image_url text,
  status varchar(20) NOT NULL DEFAULT 'unverified' CHECK (status IN ('verified','community','unverified')),
  approval_status varchar(20) NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending','approved','rejected')),
  submitted_by uuid REFERENCES users(id) ON DELETE SET NULL,
  reviewed_by uuid REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
)`;

await sql`CREATE INDEX IF NOT EXISTS markers_approval_idx ON markers(approval_status)`;
await sql`CREATE INDEX IF NOT EXISTS markers_type_idx ON markers(type)`;

console.log("THARAT database initialized.");
