-- V5.16 UI/Admin/Discord migration. Run statements individually in Neon if needed.
ALTER TABLE users ADD COLUMN IF NOT EXISTS discord_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS users_discord_id_idx ON users(discord_id) WHERE discord_id IS NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_until TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS user_warnings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id UUID REFERENCES users(id) ON DELETE CASCADE,admin_id UUID REFERENCES users(id) ON DELETE SET NULL,reason TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS user_warnings_user_idx ON user_warnings(user_id,created_at DESC);
